spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/jwt_security
    username: postgres
    password: 123@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect